FROM ghcr.io/open-edge-platform/edge-ai-libraries/intel/edge-ai-dlstreamer:20250729_EAL1.2_DLS_RC2-ubuntu22

USER root
WORKDIR /
RUN pip install --no-cache-dir python-dotenv

COPY configs/workload_to_pipeline.json /home/pipeline-server/configs/workload_to_pipeline.json
COPY configs/camera_to_workload.json /home/pipeline-server/configs/camera_to_workload.json
COPY models /home/pipeline-server/models
COPY performance-tools/sample-media /home/pipeline-server/sample-media
COPY src/run-pipeline.sh scripts/
COPY src/gst-pipeline-generator.py scripts/
COPY src/res/* res/


RUN chmod +x scripts/run-pipeline.sh

ENTRYPOINT ["scripts/run-pipeline.sh"]
